name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: your-ecr-repository-url
  ECS_SERVICE: example-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REPOSITORY/my-nodejs-app:latest.
          docker push $ECR_REPOSITORY/my-nodejs-app:latest

      - name: Update ECS task definition
        run: |
          aws ecs update-task-definition --cluster $ECS_SERVICE --task-definition example-task-definition --requires-compatibilities FARGATE

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster $ECS_SERVICE --service $ECS_SERVICE --task-definition example-task-definition
